[package]

name = "gopher"
version = "0.0.3"
authors = ["Tom Jakubowski <tom@crystae.net>"]

description = "Gopher protocol implementation"
keywords = ["gopher", "protocols"]
license = "MIT"
repository = "https://github.com/tomjakubowski/gopher-rs"
